In [1]:
import torch
import numpy as np


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/macbookpro/Desktop/AI SIBERIA/Computer Vision /.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/macbookpro/Desktop/AI SIBERIA/Computer Vision /.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/macbookpro/Desktop/AI SIBERIA/Computer Vision /.venv/lib/py

In [2]:
x = torch.tensor([[2., -1.],
                  [1., 1.]], requires_grad=True)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [3]:
out = x.pow(2).sum()

In [4]:
out.backward() # the gradient will be calculated

In [5]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])

In [6]:
# Device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [7]:
device

'cpu'

### Building A Neural Network using Pytorch

In [8]:
# Let's build a toy dataset
x = [[1,2],
     [3,4],
     [5,6],
     [7,8]]
y = [[3],
     [7],
     [11],
     [15]]

In [9]:
print(type(x), type(y))

<class 'list'> <class 'list'>


In [10]:
# convert the input and output from list to tensor objects
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [11]:
print(type(X), type(Y))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [12]:
X = X.to(device)
Y = Y.to(device)

In [13]:
import torch.nn as nn

In [14]:
nn.Linear(2,7)

Linear(in_features=2, out_features=7, bias=True)

In [15]:
# Build the neural network architecture
class ANN(nn.Module):
    def __init__(self):
        super().__init__()
        
        # define layers in the neural network
        self.input_layer = nn.Linear(2, 8)
        self.hidden_layer_activation = nn.ReLU()
        self.output_layer = nn.Linear(8, 1)
        
    # define forward pass for forward propagation
    def forward(self, x):
        x = self.input_layer(x)
        x = self.hidden_layer_activation(x)
        x = self.output_layer(x)
        return x 

In [16]:
my_net = ANN()
my_net.input_layer.weight # initial weight assigned to the neural network

Parameter containing:
tensor([[ 0.5263, -0.5546],
        [-0.5944, -0.2907],
        [-0.2716, -0.3322],
        [-0.5873, -0.1038],
        [ 0.3517,  0.1169],
        [ 0.0037, -0.2484],
        [-0.2375, -0.5241],
        [-0.2578, -0.0269]], requires_grad=True)

In [17]:
for par in my_net.parameters():
    print(par)

Parameter containing:
tensor([[ 0.5263, -0.5546],
        [-0.5944, -0.2907],
        [-0.2716, -0.3322],
        [-0.5873, -0.1038],
        [ 0.3517,  0.1169],
        [ 0.0037, -0.2484],
        [-0.2375, -0.5241],
        [-0.2578, -0.0269]], requires_grad=True)
Parameter containing:
tensor([-0.5047, -0.4671, -0.3782,  0.3715, -0.1078,  0.4593, -0.6132,  0.0950],
       requires_grad=True)
Parameter containing:
tensor([[ 0.0264, -0.0567, -0.0281,  0.3303,  0.0610, -0.0557, -0.2977, -0.2853]],
       requires_grad=True)
Parameter containing:
tensor([0.0694], requires_grad=True)


In [18]:
loss_func = nn.MSELoss() # loss function for continous variable prediction

In [19]:
_Y = my_net(X) # prediction from forward pass
loss_value = loss_func(_Y, Y) # when computing loss, always send the prediction first before the ground truth.
print(loss_value)

tensor(97.1502, grad_fn=<MseLossBackward0>)


In [20]:
# Time for some optimization
from torch.optim import SGD
optimizer  = SGD(my_net.parameters(), lr=0.001)

In [21]:
loss_history = []
for _ in range(50):
    optimizer.zero_grad() # flush previous epoch's gradient
    loss_value = loss_func(my_net(X), Y) # compute loss
    loss_value.backward() # perform backpropagation
    optimizer.step() # update weights according  to the gradient computed
    loss_history.append(loss_value)
    

In [22]:
# from matplotlib import pyplot as plt
import matplotlib.pyplot as plt

plt.plot(loss_history[:20])
plt.title("Loss Values VS Epochs")
plt.xlabel("Epochs")
plt.ylabel("Loss Value")

RuntimeError: Numpy is not available

In [23]:
import sys
print(sys.executable)

/Users/macbookpro/Desktop/AI SIBERIA/Computer Vision /.venv/bin/python


In [24]:
print("NumPy version:", np.__version__)
print("Matplotlib version:", matplotlib.__version__)

NumPy version: 2.0.1
Matplotlib version: 3.9.1
